milestone 1:  using luxon.js to create the date
Khanetmoi/Awsome_books pull request #1
Opened 2022-06-04 09:38 UTC by Khanetmoi

Awesome books: with ES6

in this project, I: 
         -separated the javascript code into different files
         - used the luxon.js library to generate the date and time

2022-06-04 10:39 UTC, codepantha requested changes
# STATUS: REQUESTED CHANGES ♻️ 

## Hi @Khanetmoi 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif"/>

### Highlights ⭐ 
✔️ Descriptive PR
✔️ Linter checks
✔️ Good design

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 10:39 UTC, codepantha commented on modules/book.js
> +      bookCard.remove();
- [ ] Please use ES6 arrow function expressions as required 🙏

2022-06-04 10:39 UTC, codepantha commented on modules/book.js
> +    }
- [ ] Please remove commented lines of code. Committing commented code makes your work look untidy 👍

2022-06-06 15:25 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @Khanetmoi 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-06 17:44 UTC, merged